import matplotlib.pyplot as plt
from matplotlib.patches import Arc
from mplsoccer import Pitch, VerticalPitch
import pandas as pd

def createPitch(base,formation):

    pitch = VerticalPitch(line_color='blue',half=False)
    fig, ax = pitch.draw()

    if (formation == '4-2-3-1'):
        plt.scatter(base[base['No']==0]['X'],base[base['No']==0]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==1]['X'],base[base['No']==1]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==2]['X'],base[base['No']==2]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==3]['X'],base[base['No']==3]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==4]['X'],base[base['No']==4]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==5]['X'],base[base['No']==5]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==6]['X'],base[base['No']==6]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==7]['X'],base[base['No']==7]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==8]['X'],base[base['No']==8]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==9]['X'],base[base['No']==9]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==10]['X'],base[base['No']==10]['Y'], color='red',marker='o', s=150)
    elif (formation == '4-1-2-1-2'):
        plt.scatter(base[base['No']==11]['X'],base[base['No']==11]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==12]['X'],base[base['No']==12]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==13]['X'],base[base['No']==13]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==14]['X'],base[base['No']==14]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==15]['X'],base[base['No']==15]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==16]['X'],base[base['No']==16]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==17]['X'],base[base['No']==17]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==18]['X'],base[base['No']==18]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==19]['X'],base[base['No']==19]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==20]['X'],base[base['No']==20]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==21]['X'],base[base['No']==21]['Y'], color='red',marker='o', s=150)
    elif (formation == '3-4-2-1'):
        plt.scatter(base[base['No']==22]['X'],base[base['No']==22]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==23]['X'],base[base['No']==23]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==24]['X'],base[base['No']==24]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==25]['X'],base[base['No']==25]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==26]['X'],base[base['No']==26]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==27]['X'],base[base['No']==27]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==28]['X'],base[base['No']==28]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==29]['X'],base[base['No']==29]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==30]['X'],base[base['No']==30]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==31]['X'],base[base['No']==31]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==32]['X'],base[base['No']==32]['Y'], color='red',marker='o', s=150)
    elif (formation == '4-3-1-2'):
        plt.scatter(base[base['No']==33]['X'],base[base['No']==33]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==34]['X'],base[base['No']==34]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==35]['X'],base[base['No']==35]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==36]['X'],base[base['No']==36]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==37]['X'],base[base['No']==37]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==38]['X'],base[base['No']==38]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==39]['X'],base[base['No']==39]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==40]['X'],base[base['No']==40]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==41]['X'],base[base['No']==41]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==42]['X'],base[base['No']==42]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==43]['X'],base[base['No']==43]['Y'], color='red',marker='o', s=150)
    elif (formation == '4-4-2'):
        plt.scatter(base[base['No']==44]['X'],base[base['No']==44]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==45]['X'],base[base['No']==45]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==46]['X'],base[base['No']==46]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==47]['X'],base[base['No']==47]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==48]['X'],base[base['No']==48]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==49]['X'],base[base['No']==49]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==50]['X'],base[base['No']==50]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==51]['X'],base[base['No']==51]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==52]['X'],base[base['No']==52]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==53]['X'],base[base['No']==53]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==54]['X'],base[base['No']==54]['Y'], color='red',marker='o', s=150)
    elif (formation == '4-3-3'):
        plt.scatter(base[base['No']==55]['X'],base[base['No']==55]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==56]['X'],base[base['No']==56]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==57]['X'],base[base['No']==57]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==58]['X'],base[base['No']==58]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==59]['X'],base[base['No']==59]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==60]['X'],base[base['No']==60]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==61]['X'],base[base['No']==61]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==62]['X'],base[base['No']==62]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==63]['X'],base[base['No']==63]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==64]['X'],base[base['No']==64]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==65]['X'],base[base['No']==65]['Y'], color='red',marker='o', s=150)
    elif (formation == '4-2-2-2'):
        plt.scatter(base[base['No']==66]['X'],base[base['No']==66]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==67]['X'],base[base['No']==67]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==68]['X'],base[base['No']==68]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==69]['X'],base[base['No']==69]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==70]['X'],base[base['No']==70]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==71]['X'],base[base['No']==71]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==72]['X'],base[base['No']==72]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==73]['X'],base[base['No']==73]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==74]['X'],base[base['No']==74]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==75]['X'],base[base['No']==75]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==76]['X'],base[base['No']==76]['Y'], color='red',marker='o', s=150)
    elif (formation == '4-4-1-1'):
        plt.scatter(base[base['No']==77]['X'],base[base['No']==77]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==78]['X'],base[base['No']==78]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==79]['X'],base[base['No']==79]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==80]['X'],base[base['No']==80]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==81]['X'],base[base['No']==81]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==82]['X'],base[base['No']==82]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==83]['X'],base[base['No']==83]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==84]['X'],base[base['No']==84]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==85]['X'],base[base['No']==85]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==86]['X'],base[base['No']==86]['Y'], color='red',marker='o', s=150)
        plt.scatter(base[base['No']==87]['X'],base[base['No']==87]['Y'], color='red',marker='o', s=150)

    # plt.show()
    return fig